CREATE DATABASE inventory_fw;
USE inventory_fw;

CREATE TABLE USERS (
    ID INT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTS (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    PRICE FLOAT(10,2) NOT NULL,
    CREATED_BY INT NOT NULL,
    PRIMARY KEY (ID),  -- Agregada la coma aquí
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
);

CREATE TABLE ROLE (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLE (
    ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);
